{
 "title": "机翻站数据看板",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "系统网络传输速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "接收速率"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{interface=\"eth0\"}[5m]))",
     "legendFormat": "发送速率"
    }
   ]
  },
  {
   "title": "系统硬盘读写速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{id=\"/\"}[5m])",
     "legendFormat": "Write速率"
    },
    {
     "expr": "-irate(container_fs_reads_bytes_total{id=\"/\"}[5m])",
     "legendFormat": "Read速率"
    }
   ]
  },
  {
   "title": "CPU 占用",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m])) by (container_label_com_docker_compose_project) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (container_label_com_docker_compose_project)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "网络接收速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\"}[5m])) by (container_label_com_docker_compose_project)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "硬盘 Read 速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{image!=\"\"}[5m])) by (container_label_com_docker_compose_project)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "硬盘 Write 速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{image!=\"\"}[5m])) by (container_label_com_docker_compose_project)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "网络发送速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\"}[5m])) by (container_label_com_docker_compose_project)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "AutoNovel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU 占用",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "网络接收速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "网络发送速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "硬盘 Write 速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "硬盘 Read 速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"auto-novel\"}[5m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}