{
 "title": "SakuraShare",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "实时数据",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(proxy_requests_by_model_tokens_total[30s]) * (proxy_node_by_model !=  bool 0) ",
     "legendFormat": "{{model}}"
    },
    {
     "expr": "sum(irate(proxy_requests_by_model_tokens_total[30s]))",
     "legendFormat": "总算力"
    },
    { "expr": "slots_processing", "legendFormat": "正在处理的 Slots" }
   ]
  },
  {
   "title": "每个模型的贡献者计数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "proxy_node_by_model > 0", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Req Referer Count in 30s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "increase(proxy_requests_by_referer_total[30s]) > 0 ",
     "legendFormat": "{{referer}}"
    }
   ]
  },
  {
   "title": "30秒全网平均总算力 t/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "irate(proxy_requests_by_model_tokens_total[30s]) > 0 ",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Running Slots",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    { "expr": "slots_processing", "legendFormat": "running slots" }
   ]
  },
  {
   "title": "Reqs Stats",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "increase(proxy_requests_fail_total[$__rate_interval])",
     "legendFormat": "错误"
    },
    {
     "expr": "increase(proxy_requests_success_total[$__rate_interval])",
     "legendFormat": "成功"
    },
    {
     "expr": "increase(proxy_requests_total[$__rate_interval]) ",
     "legendFormat": "总计"
    }
   ]
  },
  {
   "title": "单个 Slots 算力（1min 内） t/s ",
   "type": "timeseries",
   "description": "按模型计算的所有 slots 平均算力",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(proxy_requests_by_model_tokens_total[1m]) / rate(proxy_requests_by_model_latency_total[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "贡献者算力 (t/s)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "irate(proxy_tokens_by_node_total[30s])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "模型退化计数（百分比，总计+1Min）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "proxy_degradation_by_model_total / proxy_requests_by_model_total * 100",
     "legendFormat": "Total ({{model}})"
    },
    {
     "expr": "increase(proxy_degradation_by_model_total[1m]) / increase(proxy_requests_by_model_total[1m]) * 100 > 0 ",
     "legendFormat": "1m-{{model}}"
    }
   ]
  },
  {
   "title": "贡献者单slot算力 (t/s)「负算力=临时封禁」",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "targets": [
    { "expr": "proxy_load_by_node", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "贡献者负载(slots)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "targets": [
    { "expr": "proxy_slots_by_node ", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "贡献者退化计数（1min-百分比）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "increase(proxy_degradation_by_node_total[1m]) / increase(proxy_processed_by_node_total[1m]) * 100 > 0",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}